### ISSUE TITLE
Disenchant Value issue.

### ISSUE THREAD

**Issue by jclock** [shirsig/aux-addon#53] opened 2016-12-29 19:39 UTC
Disenchant value shows at "--" with items that can DE into Nexus Crystals. I believe it is because there is no price available for it, even if there is a price for Large Brilliant Shards.

**Comment by shirsig** [comment] 2016-12-29 19:43
True, but that's not a bug. The disenchant value is a weighted average and there's no way to compute it if there aren't prices for all components.

**Comment by jclock** [comment] 2016-12-30 03:11
Please correct me if I am wrong, but shouldn't it still calculate some sort of price (albeit wrong). Say we have LBS price of 5g, and Nexus price of 0g, since it can not be found. DE % would be 99.5% and 0.5% respectively

5g * 0.995 + 0g * 0.005 = 4.975g value.

Or is it that because it can not find a price it is not being assigned a value of 0g? If that is the case, a check to see if the value exists, and if it doesn't ignore it from the averaging?

**Comment by shirsig** [comment] 2016-12-30 08:13
It makes no sense to assign it 0 when there isn't a price. Might as well assign it 100g or just a random value.

Ignoring it in this case it wouldn't be so bad because nexus crystal has a small weight but consider the reverse, what if there is a price for nexus crystal but none for the shard, then it would show the nexus crystal value as the disenchant value?

**Comment by jclock** [comment] 2016-12-30 17:50
Eventually a scan would pick up the LBS price, but the Nexus Crystal isn't implemented until AQ comes out.

**Comment by shirsig** [comment] 2017-01-02 19:00
Well, this is a problem with nost's gradual release of content which is rather different than just not having scanned something. The correct solution would be to adapt the disenchant produce, but unfortunately I can't think of a way to detect the server's current progress so you would have to manually edit the lua file.

**Comment by jclock** [comment] 2017-01-02 23:35
Would there be a way to query the server to see if the item exists?

**Comment by shirsig** [comment] 2017-01-02 23:42
Well, sort of. I think you're not supposed to be able to click a link if an item doesn't exist yet. Not sure how reliable this is though. For example on nost pve naxx item links aren't clickable but the nexus crystal link is, so it definitely couldn't detect this.

**Comment by jclock** [comment] 2017-01-03 00:11
Damn, oh well. I'll manually edit it I guess. Also, as a note for anyone making the edit, I believe the 51+ epics would also be edited due to this, since they wouldn't result in a crystal. Changing 20725 to 14344 should do it for now.

**Closed** 2017-01-11 19:57 UTC
