### ISSUE TITLE
Changing price with backspace/delete does not work

### ISSUE THREAD

**Issue by wodim** [shirsig/aux-addon#179] opened 2018-09-08 10:21 UTC
If you modify the price of an auction when posting it using backspace or delete and then use tab to switch to the other field, the change is undone.

**Comment by shirsig** [comment] 2019-01-27 06:38
Known issue but surprisingly difficult to fix due to how the input events work in vanilla. There's an event that fires whenever the text changes but the problem is it fires also when it's not changing from user input and doesn't tell you how it was triggered. Then there's another event that only fires from user input but it is not triggered by all input (e.g., not by backspace and delete).

**Comment by shirsig** [comment] 2020-05-30 12:30
fixed in the classic version

**Closed by shirsig** 2020-05-30 12:30 UTC
