### ISSUE TITLE
Can't Post Item

### ISSUE THREAD

**Issue by SecretKosmoNaut** [shirsig/aux-addon#228] opened 2019-09-08 21:10 UTC
Not sure why, but whenever I click on the item listed in the Post tab, it doesn't work. Where can I find log information to narrow down the root cause so that I can provide it here?

**Comment by kakkakk** [comment] 2019-09-09 03:40
Post also does not work for me, before this latest version or after. Deleted all traces of the previous versions from \addons and \wtf before installation.

**Comment by shirsig** [comment] 2019-09-09 04:45
Strange, it works fine for me. Maybe you didn't log out before deleting the WTF files? Because then they would just be rewritten from cache.

**Comment by kakkakk** [comment] 2019-09-09 05:16
Yup, I'm aware. I can try again. Thanks for getting back to me.

**Comment by kakkakk** [comment] 2019-09-09 05:18
Still no-go, fresh install of the addon after aux-addon.lua and it's .bak
have been removed. At least one other person posted the same problem as me
though :)

**Comment by shirsig** [comment] 2019-09-09 05:37
Hm, can you enable lua errors and copy here what you get please? /console scriptErrors 1

**Comment by kakkakk** [comment] 2019-09-09 05:45
That's the interesting thing, it's not throwing any errors. (I've kept lua
errors enabled since classic launch, it's been helpful in identifying a few
troublesome addons) But with aux... neither right clicking on an object in
my bags, nor dragging an object into the appropriate area on the Post tab
works.

**Comment by shirsig** [comment] 2019-09-09 05:52
Oh, that's the problem, that's not a bug. Right clicking is not possible so I changed it to alt-click. Not sure if dragging was already removed from the latest vanilla version or of it's broken. Anyway, you can also click the items in the list within aux, which is the intended way to do it.

**Comment by kakkakk** [comment] 2019-09-10 17:00
Thank you for taking the time to clarify! I always just right clicked from
my bags while using the addon on private vanilla servers. I will alt click
from now on or use the list built into the addon. Cheers!

**Comment by SecretKosmoNaut** [comment] 2019-09-11 22:00
Here's the error I receive, it wasn't showing an error before but now it's popping up in a GUI box:

Date: 2019-09-11 14:58:51
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\aux-addon\util\money.lua line 62:
   attempt to compare nil with number
Debug:
   aux-addon\util\money.lua:62: to_string()
   aux-addon\tabs\post\core.lua:400: update_item()
   aux-addon\tabs\post\frame.lua:63:
      aux-addon\tabs\post\frame.lua:61
Locals:
money = nil
pad = true
trim = nil
color = nil
no_color = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare nil with number"
T = <table> {
}
aux = <table> {
}

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AccountantClassic, vv2.11.08.11302
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AutoLootPlus, v2.0.0-11302
  auxaddon, v0.2.2
  BagBrother, v
  Bagnon, v8.2.9
  Bartender4, v4.8.7
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  Enchantrix, v8.2.6392 (SwimmingSeadragon)
  GatherMate2, v1.45
  Informant, v8.2.6374 (SwimmingSeadragon)
  Questie, v4.0.18 BETA
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=38b)

**Comment by helllllpppp** [comment] 2019-09-12 04:31
Also having the same problem with a specific item.

Message: Interface\AddOns\aux-addon\util\money.lua:62: attempt to compare nil with number
Time: Thu Sep 12 00:27:05 2019
Count: 5
Stack: Interface\AddOns\aux-addon\util\money.lua:62: attempt to compare nil with number
Interface\AddOns\aux-addon\util\money.lua:62: in function `to_string'
Interface\AddOns\aux-addon\tabs\post\core.lua:401: in function `update_item'
Interface\AddOns\aux-addon\tabs\post\frame.lua:63: in function <Interface\AddOns\aux-addon\tabs\post\frame.lua:61>

Locals: money = nil
pad = true
trim = nil
color = nil
no_color = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare nil with number"
T = <table> {
}
aux = <table> {
}

**Comment by tyggyr** [comment] 2019-09-14 02:17
I believe the fix is in aux-addon\util\money.lua
```
function M.to_string(money, pad, trim, color, no_color)
+	if not money then
+		money = 0
+	end
```
Lua errors were telling me that money was nil.
Sorry I have no diff for this.

**Comment by shirsig** [comment] 2019-09-14 06:45
It's not really a fix, it's kind of dangerous. The money there should not be 0, that's the real problem.
Strange that only a few people have this issue. For some it will definitely be a savedvariables issue, but since it didn't fix it for everyone dunno ...
Could you try to disable all other addons to see if it's an addon conflict?

**Comment by tyggyr** [comment] 2019-09-14 23:44
I'll back the change out and then when it reproduces I'll do the disable
others; I expect that it won't help since nuking the saved variables
"fixed" it for me last time... temporarily.

**Comment by SecretKosmoNaut** [comment] 2019-09-15 03:21
Deleting the file you mentioned previously worked. Should I leave this ticket open for reference?

**Comment by tyggyr** [comment] 2019-09-19 00:34
Disabling all other addons, the problem still occurs.

**Comment by tyggyr** [comment] 2019-09-19 00:37
I'll note that money isn't zero, it's nil. I'm definitely not a lua expert but I think there's a difference.

**Comment by shirsig** [comment] 2019-09-22 21:30
With the newest version try **/aux clear post** or **/aux clear item cache** and **/run ReloadUI()**

**Comment by GuerraReturns** [comment] 2019-09-27 23:27
> With the newest version try **/aux clear post** or **/aux clear item cache** and **/run ReloadUI()**

Not work.

There are a real fix? I have all my items bloked for this error too :

Message: Interface\AddOns\aux-addon\util\money.lua:62: attempt to compare nil with number
Time: Sat Sep 28 01:21:59 2019
Count: 2
Stack: Interface\AddOns\aux-addon\util\money.lua:62: attempt to compare nil with number
Interface\AddOns\aux-addon\util\money.lua:62: in function `to_string'
Interface\AddOns\aux-addon\tabs\post\core.lua:401: in function `update_item'
Interface\AddOns\aux-addon\tabs\post\frame.lua:63: in function <Interface\AddOns\aux-addon\tabs\post\frame.lua:61>

Locals: money = nil
pad = true
trim = nil
color = nil
no_color = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare nil with number"
T = <table> {
}
aux = <table> {
}


We need find a fix, a lot of people have this problem

**Closed** 2019-10-19 11:47 UTC
